name: run black and isort
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install isort and black
        run: pip install isort black
      - name: Run isort
        run: isort --check --diff .
      - name: Run black
        run: black --check --diff .
